### ISSUE TITLE
Max cannot be reached sometimes based on step size

### ISSUE THREAD

**Issue by smares** [ktsn/vue-range-slider#34] opened 2018-05-09 09:55 UTC
If you have the slider set to `:min="1"`, `:max="1000"` and `:step="10"`, you can never reach a value of 1000, the slider stops at 991.

Also, it would be nice if it was possible to allow something like `:min="1"`, `:max="1000"`, `:step="10"`, but have the steps be a multiple of 10, so it would go like 1, 10, 20, 30, ..., 980, 990, 1000, but I am not sure how this can be configured in a logical way.

**Comment by ktsn** [comment] 2018-05-09 11:57
duplicate of #23

**Closed as completed** 2018-05-09 11:57 UTC
